export const fruits = [
  {
    id: '1',
    name: 'fruits',
    image: require('../assets/CategoriesPhoto/Fruits/Apples.png'),
    productName: 'Fresh Red Apples',
    price: '₹150/kg',
    minOrderQty: '10 kg',
    location: 'Shimla, India',
    farmerName:'piyush',
  },
  {
    id: '2',
    name: 'fruits',
    image: require('../assets/CategoriesPhoto/Fruits/Green Bananas.png'),
    productName: 'Organic Green Bananas',
    price: '₹30/kg',
    minOrderQty: '15 kg',
    location: 'Kerala, India',
    farmerName:'Sarvanna',
  },
  {
    id: '3',
    name: 'fruits',
    image: require('../assets/CategoriesPhoto/Fruits/Oranges.png'),
    productName: 'Juicy Oranges',
    price: '₹80/kg',
    minOrderQty: '12 kg',
    location: 'Nagpur, India',
    farmerName:'Harsh',
  },
  {
    id: '4',
    name: 'fruits',
    image: require('../assets/CategoriesPhoto/Fruits/Pomogranate.png'),
    productName: 'Fresh Pomegranate',
    price: '₹120/kg',
    minOrderQty: '10 kg',
    location: 'Pune, India',
    farmerName:'Sushant',
  },

    {
    id: '5',
    name: 'fruits',
    image: require('../assets/CategoriesPhoto/Fruits/Pineapple.png'),
    productName: 'Sweet Pineapples',
    price: '₹50/kg',
    minOrderQty: '5 kg',
    location: 'Assam, India',
    farmerName:'Divesh',
  },
  {
    id: '6',
    name: 'fruits',
    image: require('../assets/CategoriesPhoto/Fruits/Grapes.png'),
    productName: 'Fresh Green Grapes',
    price: '₹90/kg',
    minOrderQty: '8 kg',
    location: 'Nashik, India',
    farmerName:'Sanket',
  }
];


